### ISSUE TITLE
Feature Request: Tick Box with javascript localstorage

### ISSUE THREAD

**Issue by PandaPandaPanda** [matthewtheinventor/watnext#1]
Could you add tick-box functionality and store data with localstorage or cache? That would make the site even better.
The process shouldn't be hard either.

Or if you allow me to fork the source code, so I can implement this feature.

**Comment by matthewtheinventor** [comment]
Source code for the entire app has been uploaded, feel free to fork.

**Comment by PandaPandaPanda** [comment]
Great, but it is missing the package.json file
